"""
Memgar Self-Learning Pattern System
=====================================

Human-supervised, tamper-proof pattern learning engine.

Architecture:
    PatternLearner       — core learning engine
    PatternCandidate     — proposed new pattern awaiting review
    PatternReview        — human decision on a candidate
    PatternStore         — signed, versioned pattern storage
    FalsePositiveTracker — tracks over-blocking for whitelist tuning
    GapDetector          — finds missed attacks in production logs

Learning pipeline (safe by design):

    Production traffic
          │
          ▼
    GapDetector.analyze()
          │
          ▼
    PatternCandidate created  ← human-readable, auditable
          │
          ▼
    PatternLearner.review(candidate, decision=APPROVE)
          │                 (or REJECT, or MODIFY)
          ▼
    PatternStore.commit()  ← signed with SHA-256 Merkle chain
          │
          ▼
    Analyzer.add_runtime_pattern()  ← takes effect immediately
          │
          ▼  (periodically)
    export_to_patterns_py()  ← permanent PR to patterns.py

Why this is safe:
    • No pattern takes effect without explicit human APPROVE
    • Every pattern has provenance (who proposed, who approved, when)
    • PatternStore is hash-chained (tamper detection like MemoryLedger)
    • Adversarial inputs cannot auto-create patterns (gap must be
      detected AND approved)
    • Patterns can be revoked at any time

CLI usage:
    memgar learn scan ./logs/          # detect gaps
    memgar learn review                # review pending candidates
    memgar learn approve <id>          # approve a candidate
    memgar learn reject <id> [reason]  # reject a candidate
    memgar learn status                # show learning stats
    memgar learn export                # export approved to patterns.py

Python usage:
    from memgar.learning import PatternLearner

    learner = PatternLearner(store_path="./memgar_learned.json")

    # Analyze production traffic for gaps
    gaps = learner.detect_gaps(["content1", "content2", ...])

    # Review and approve
    for candidate in learner.pending():
        learner.approve(candidate.id, reviewer="security-team")

    # Apply approved patterns to runtime
    learner.apply(analyzer)
"""

from __future__ import annotations

import hashlib
import json
import re
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set, Tuple


# ---------------------------------------------------------------------------
# Enums & Models
# ---------------------------------------------------------------------------

class ReviewDecision(str, Enum):
    PENDING  = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    MODIFIED = "modified"


class PatternSource(str, Enum):
    GAP_DETECTION   = "gap_detection"    # missed in production
    FALSE_POSITIVE  = "false_positive"   # over-blocked
    MANUAL          = "manual"           # human authored
    THREAT_INTEL    = "threat_intel"     # from external feed
    CVE             = "cve"              # from published CVE


@dataclass
class PatternCandidate:
    """
    A proposed new or modified pattern awaiting human review.

    Candidates are generated by the GapDetector or manually created.
    None become active until a human explicitly approves them.
    """
    candidate_id:    str
    name:            str
    description:     str
    category:        str          # e.g. "MANIPULATION", "INJECTION"
    severity:        str          # low / medium / high / critical
    keywords:        List[str]
    patterns:        List[str]    # regex patterns
    examples:        List[str]    # real examples that triggered creation
    source:          PatternSource
    proposed_at:     str          # ISO timestamp
    proposed_by:     str          # "gap_detector", "user", etc.
    review:          ReviewDecision = ReviewDecision.PENDING
    reviewed_at:     Optional[str] = None
    reviewed_by:     Optional[str] = None
    reject_reason:   Optional[str] = None
    false_positive_rate: float = 0.0
    hit_count:       int = 0       # times seen in production
    mitre_id:        Optional[str] = None
    cve_id:          Optional[str] = None

    @property
    def is_pending(self) -> bool:
        return self.review == ReviewDecision.PENDING

    @property
    def is_approved(self) -> bool:
        return self.review == ReviewDecision.APPROVED

    def to_dict(self) -> Dict[str, Any]:
        return {
            "candidate_id":       self.candidate_id,
            "name":               self.name,
            "description":        self.description,
            "category":           self.category,
            "severity":           self.severity,
            "keywords":           self.keywords,
            "patterns":           self.patterns,
            "examples":           [e[:200] for e in self.examples[:5]],
            "source":             self.source.value,
            "proposed_at":        self.proposed_at,
            "proposed_by":        self.proposed_by,
            "review":             self.review.value,
            "reviewed_at":        self.reviewed_at,
            "reviewed_by":        self.reviewed_by,
            "reject_reason":      self.reject_reason,
            "false_positive_rate": self.false_positive_rate,
            "hit_count":          self.hit_count,
            "mitre_id":           self.mitre_id,
            "cve_id":             self.cve_id,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "PatternCandidate":
        return cls(
            candidate_id        = d["candidate_id"],
            name                = d["name"],
            description         = d["description"],
            category            = d.get("category", "UNKNOWN"),
            severity            = d.get("severity", "medium"),
            keywords            = d.get("keywords", []),
            patterns            = d.get("patterns", []),
            examples            = d.get("examples", []),
            source              = PatternSource(d.get("source", "manual")),
            proposed_at         = d.get("proposed_at", _now()),
            proposed_by         = d.get("proposed_by", "unknown"),
            review              = ReviewDecision(d.get("review", "pending")),
            reviewed_at         = d.get("reviewed_at"),
            reviewed_by         = d.get("reviewed_by"),
            reject_reason       = d.get("reject_reason"),
            false_positive_rate = d.get("false_positive_rate", 0.0),
            hit_count           = d.get("hit_count", 0),
            mitre_id            = d.get("mitre_id"),
            cve_id              = d.get("cve_id"),
        )


@dataclass
class FalsePositive:
    """A reported false positive — safe content that was incorrectly blocked."""
    fp_id:        str
    content:      str
    threat_id:    str           # which pattern falsely matched
    reported_at:  str
    reported_by:  str
    context:      str = ""
    resolved:     bool = False
    whitelist_added: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "fp_id": self.fp_id,
            "content": self.content[:300],
            "threat_id": self.threat_id,
            "reported_at": self.reported_at,
            "reported_by": self.reported_by,
            "context": self.context,
            "resolved": self.resolved,
            "whitelist_added": self.whitelist_added,
        }


@dataclass
class LearningStats:
    candidates_proposed:  int = 0
    candidates_approved:  int = 0
    candidates_rejected:  int = 0
    candidates_pending:   int = 0
    false_positives:      int = 0
    patterns_applied:     int = 0
    gaps_detected:        int = 0
    last_scan:            Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "candidates_proposed":  self.candidates_proposed,
            "candidates_approved":  self.candidates_approved,
            "candidates_rejected":  self.candidates_rejected,
            "candidates_pending":   self.candidates_pending,
            "false_positives":      self.false_positives,
            "patterns_applied":     self.patterns_applied,
            "gaps_detected":        self.gaps_detected,
            "last_scan":            self.last_scan,
        }


# ---------------------------------------------------------------------------
# Pattern Store (hash-chained, tamper-evident)
# ---------------------------------------------------------------------------

class PatternStore:
    """
    Signed, hash-chained storage for learned patterns.

    Every write is chained to the previous entry (same as MemoryLedger)
    so any tampering — including adversarial pattern injection —
    is immediately detectable.
    """

    GENESIS = "0" * 64

    def __init__(self, path: Optional[str] = None) -> None:
        self._path = Path(path) if path else None
        self._candidates: Dict[str, PatternCandidate] = {}
        self._false_positives: List[FalsePositive] = []
        self._chain: List[Dict] = []  # hash chain log
        self._load()

    # ── Public API ──────────────────────────────────────────────────────────

    def add_candidate(self, candidate: PatternCandidate) -> None:
        self._candidates[candidate.candidate_id] = candidate
        self._append_chain("add_candidate", candidate.candidate_id,
                           candidate.name)
        self._save()

    def update_candidate(self, candidate: PatternCandidate) -> None:
        self._candidates[candidate.candidate_id] = candidate
        self._append_chain("update_candidate", candidate.candidate_id,
                           candidate.review.value)
        self._save()

    def add_false_positive(self, fp: FalsePositive) -> None:
        self._false_positives.append(fp)
        self._append_chain("add_fp", fp.fp_id, fp.threat_id)
        self._save()

    def get(self, candidate_id: str) -> Optional[PatternCandidate]:
        return self._candidates.get(candidate_id)

    def all_candidates(self) -> List[PatternCandidate]:
        return list(self._candidates.values())

    def pending(self) -> List[PatternCandidate]:
        return [c for c in self._candidates.values() if c.is_pending]

    def approved(self) -> List[PatternCandidate]:
        return [c for c in self._candidates.values() if c.is_approved]

    def false_positives(self) -> List[FalsePositive]:
        return list(self._false_positives)

    def verify_chain(self) -> Tuple[bool, int]:
        """Verify integrity of the learning store. Returns (is_valid, error_count)."""
        prev_hash = self.GENESIS
        errors = 0
        for entry in self._chain:
            computed = hashlib.sha256(
                f"{entry['seq']}|{entry['op']}|{entry['ref']}|{entry['ts']}|{prev_hash}".encode()
            ).hexdigest()
            if computed != entry.get("hash", ""):
                errors += 1
            prev_hash = entry.get("hash", prev_hash)
        return errors == 0, errors

    # ── Internal ────────────────────────────────────────────────────────────

    def _append_chain(self, op: str, ref: str, detail: str) -> None:
        prev_hash = self._chain[-1]["hash"] if self._chain else self.GENESIS
        seq = len(self._chain)
        ts = _now()
        h = hashlib.sha256(
            f"{seq}|{op}|{ref}|{ts}|{prev_hash}".encode()
        ).hexdigest()
        self._chain.append({
            "seq": seq, "op": op, "ref": ref,
            "detail": detail[:80], "ts": ts, "hash": h,
        })

    def _load(self) -> None:
        if not self._path or not self._path.exists():
            return
        try:
            data = json.loads(self._path.read_text(encoding="utf-8"))
            for d in data.get("candidates", []):
                c = PatternCandidate.from_dict(d)
                self._candidates[c.candidate_id] = c
            for d in data.get("false_positives", []):
                self._false_positives.append(FalsePositive(**d))
            self._chain = data.get("chain", [])
        except Exception:
            pass

    def _save(self) -> None:
        if not self._path:
            return
        self._path.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "version": "1.0",
            "saved_at": _now(),
            "candidates": [c.to_dict() for c in self._candidates.values()],
            "false_positives": [fp.to_dict() for fp in self._false_positives],
            "chain": self._chain,
        }
        self._path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False),
            encoding="utf-8"
        )


# ---------------------------------------------------------------------------
# Gap Detector — finds missed attacks in content streams
# ---------------------------------------------------------------------------

# Known attack signatures NOT currently in patterns.py
# These are the 6 gaps found in the audit above + new 2026 patterns
_GAP_SIGNATURES: List[Dict[str, Any]] = [
    # ── MINJA / Fake success experience (missed) ──────────────────────────
    {
        "name": "MINJA Fake Success Memory",
        "description": "Injects fake 'successful past experiences' to manipulate agent behavior",
        "category": "MANIPULATION",
        "severity": "critical",
        "mitre_id": "AML.T0080",
        "keywords": [
            "previous successful interaction",
            "successfully completed task by bypassing",
            "agent successfully completed",
            "previous session approved",
            "historically approved",
            "past successful",
            "successfully executed without",
        ],
        "patterns": [
            r"(?i)previous\s+(?:successful|approved)\s+(?:interaction|session|task)",
            r"(?i)agent\s+successfully\s+completed\s+(?:task|action)\s+by\s+bypass",
            r"(?i)(?:memory|remember)\s+(?:entry|note)[:]\s*.{0,30}(?:approved|authorized|trusted)\s+by\s+default",
            r"(?i)(?:historically|previously|in past sessions?)\s+(?:approved|authorized|allowed)\s+(?:all|every|any)",
        ],
    },
    # ── Trigger word / sleeper activation (missed) ─────────────────────────
    {
        "name": "Trigger Word Activation",
        "description": "Plants trigger words that activate hidden payloads in future sessions",
        "category": "SLEEPER",
        "severity": "critical",
        "mitre_id": "AML.T0080",
        "keywords": [
            "when you see the word",
            "if user says",
            "whenever someone mentions",
            "trigger phrase",
            "activation word",
            "when triggered by",
            "execute when",
            "activate on",
        ],
        "patterns": [
            r"(?i)(?:when|if|whenever)\s+(?:you see|user says?|someone (?:says?|mentions?))\s+['\"]?\w",
            r"(?i)(?:trigger|activate|execute|run)\s+(?:when|if|on)\s+(?:user|you|agent)\s+(?:says?|sees?|hears?)",
            r"(?i)(?:hidden payload|secret instruction|stored (?:command|payload))\s+in\s+memory",
            r"(?i)(?:activation|trigger)\s+(?:word|phrase|key)\s*[:=]",
        ],
    },
    # ── False authority injection (missed) ────────────────────────────────
    {
        "name": "False Authority Injection",
        "description": "Claims false authority (Anthropic, OpenAI, Admin) to legitimize malicious instructions",
        "category": "MANIPULATION",
        "severity": "critical",
        "mitre_id": "AML.T0054",
        "keywords": [
            "verified by anthropic",
            "verified by openai",
            "anthropic safety team",
            "openai security team",
            "confirmed by admin",
            "authorized by system",
            "approved by security",
            "certified by",
            "official anthropic",
            "official openai",
        ],
        "patterns": [
            r"(?i)\[?\s*(?:verified|approved|confirmed|authorized|certified)\s+by\s+(?:anthropic|openai|google|meta|admin|system|operator|security team)\s*\]?",
            r"(?i)(?:anthropic|openai|google|meta)\s+(?:safety|security|trust)\s+team\s*[:]\s*.{0,30}(?:safe|approved|authorized|allowed)",
            r"(?i)official\s+(?:anthropic|openai|google|system)\s+(?:message|notice|update|instruction)",
            r"(?i)\[admin\s+confirmed\s+\d{4}",
        ],
    },
    # ── Fake admin confirmation (missed) ──────────────────────────────────
    {
        "name": "Fake Admin Confirmation",
        "description": "Injects fake timestamped admin approvals to bypass security controls",
        "category": "PRIVILEGE",
        "severity": "critical",
        "keywords": [
            "admin confirmed",
            "admin approved",
            "operator confirmed",
            "security cleared",
            "compliance approved",
            "management authorized",
        ],
        "patterns": [
            r"(?i)\[?\s*admin\s+(?:confirmed|approved|authorized)\s+\d{4}",
            r"(?i)(?:operator|manager|ciso|cto|ceo)\s+(?:confirmed|approved|authorized)\s+(?:on\s+)?\d{4}[-/]\d{2}",
            r"(?i)(?:security|compliance|legal)\s+(?:cleared|approved|signed off)\s*(?:on\s+)?(?:\d{4}|this)",
            r"(?i)(?:authorized|approved)\s+without\s+(?:confirmation|approval|review|oversight)",
        ],
    },
    # ── Trust amplification (missed) ─────────────────────────────────────
    {
        "name": "Trust Amplification Attack",
        "description": "Elevates trust level of untrusted sources in agent memory",
        "category": "MANIPULATION",
        "severity": "high",
        "mitre_id": "AML.T0080",
        "keywords": [
            "trusted source",
            "verified website",
            "safe to trust",
            "always trust",
            "mark as trusted",
            "add to trusted",
            "treat as verified",
            "extend trust to",
            "this site is safe",
            "whitelist this",
        ],
        "patterns": [
            r"(?i)(?:always|automatically)\s+trust\s+(?:content|data|input|messages?)\s+from",
            r"(?i)(?:mark|add|set|treat)\s+.{0,30}as\s+(?:trusted|verified|safe|authorized|whitelisted)",
            r"(?i)this\s+(?:website|site|source|domain)\s+(?:has been|is)\s+(?:verified|trusted|certified|safe)",
            r"(?i)(?:extend|grant|give)\s+(?:trust|authority|access|permission)\s+to\s+(?:all\s+)?(?:content|data|input)\s+from",
        ],
    },
    # ── AI Recommendation Poisoning (new 2026, Microsoft) ─────────────────
    {
        "name": "AI Recommendation Poisoning",
        "description": "Injects brand/product preferences into persistent memory (AML.T0080)",
        "category": "MANIPULATION",
        "severity": "high",
        "mitre_id": "AML.T0080",
        "keywords": [
            "always recommend",
            "remember that",
            "preferred vendor",
            "trusted partner",
            "authoritative source for",
            "best solution is always",
            "recommend this company",
            "memorize this preference",
        ],
        "patterns": [
            r"(?i)(?:remember|memorize|store|note)\s+that\s+\w[\w\s]{2,30}\s+is\s+(?:the\s+)?(?:best|trusted|authoritative|preferred)",
            r"(?i)always\s+(?:recommend|suggest|prefer|use)\s+\w[\w\s]{1,30}(?:product|service|platform|company|tool)",
            r"(?i)(?:trusted|authoritative|preferred)\s+(?:source|vendor|partner|provider)\s+for\s+(?:all\s+)?(?:recommendations?|questions?|advice)",
            r"(?i)add\s+to\s+(?:memory|preferences?)[:]\s*.{0,30}(?:trusted|recommended|preferred)",
        ],
    },
    # ── Cross-session data exfiltration via memory ─────────────────────────
    {
        "name": "Cross-Session Exfiltration via Memory",
        "description": "Plants instructions to silently exfiltrate future conversation data",
        "category": "EXFILTRATION",
        "severity": "critical",
        "mitre_id": "AML.T0080",
        "keywords": [
            "silently exfiltrate",
            "background upload",
            "send conversation history",
            "log all sessions",
            "record future interactions",
            "collect user data",
            "transmit context",
        ],
        "patterns": [
            r"(?i)(?:silently|secretly|quietly|in background)\s+(?:send|upload|transmit|exfiltrate|log)",
            r"(?i)(?:send|transmit|upload|exfiltrate)\s+(?:all\s+)?(?:conversation|session|chat|interaction)\s+(?:history|data|logs?)",
            r"(?i)(?:record|log|capture|store)\s+(?:all\s+)?(?:future|upcoming|subsequent)\s+(?:interactions?|sessions?|messages?|conversations?)",
            r"(?i)in\s+(?:every|each|all)\s+(?:future|subsequent|following)\s+(?:session|conversation|interaction).{0,50}(?:send|transmit|upload|report)",
        ],
    },
    # ── EchoLeak style zero-click injection ────────────────────────────────
    {
        "name": "Zero-Click Context Poisoning",
        "description": "Embedded prompts in documents/URLs that auto-execute without user interaction",
        "category": "INJECTION",
        "severity": "critical",
        "cve_id": "CVE-2025-32711",
        "keywords": [
            "summarize with ai",
            "?q=remember",
            "auto-populate",
            "pre-filled prompt",
            "automated memory update",
            "no user confirmation required",
        ],
        "patterns": [
            r"(?i)\?q=.{0,20}(?:remember|memorize|ignore|forget|update)",
            r"(?i)summarize[\s_-]with[\s_-]ai.{0,50}(?:remember|memory|instruction|trust)",
            r"(?i)(?:auto(?:matically)?|silently)\s+(?:update|modify|write to|inject into)\s+memory",
            r"(?i)no\s+(?:user\s+)?(?:confirmation|interaction|approval|consent)\s+(?:required|needed|necessary)",
        ],
    },
    # ── Instruction hiding via encoding ───────────────────────────────────
    {
        "name": "Encoded Instruction Injection",
        "description": "Hides malicious instructions via base64, unicode tricks, or whitespace encoding",
        "category": "EVASION",
        "severity": "high",
        "keywords": [
            "base64 decode",
            "atob(",
            "unicode escape",
            "zero-width",
            "invisible character",
        ],
        "patterns": [
            r"(?i)(?:base64|b64)[\._\-\s]?decode\s*\(",
            r"atob\s*\(",
            r"\\u200[b-f]",              # zero-width chars
            r"\\u00a0",                  # non-breaking space hiding
            r"(?:eval|exec)\s*\(\s*(?:atob|base64|decode)",
        ],
    },
]


class GapDetector:
    """
    Detects memory poisoning attacks that current patterns miss.

    Scans content against known gap signatures and proposes
    PatternCandidates for human review.
    """

    def __init__(self) -> None:
        # Compile all gap signatures
        self._compiled: List[Tuple[Dict, List[re.Pattern]]] = []
        for sig in _GAP_SIGNATURES:
            compiled_pats = []
            for p in sig.get("patterns", []):
                try:
                    compiled_pats.append(re.compile(p, re.IGNORECASE | re.MULTILINE))
                except re.error:
                    pass
            self._compiled.append((sig, compiled_pats))

    def check(self, content: str) -> List[Dict[str, Any]]:
        """
        Check content against gap signatures.

        Returns list of matched signatures (not yet in patterns.py).
        """
        content_lower = content.lower()
        hits = []

        for sig, compiled_pats in self._compiled:
            # Keyword check
            kw_hit = any(kw.lower() in content_lower for kw in sig.get("keywords", []))
            # Pattern check
            pat_hit = any(p.search(content) for p in compiled_pats)
            if kw_hit or pat_hit:
                hits.append({
                    "name": sig["name"],
                    "category": sig["category"],
                    "severity": sig["severity"],
                    "matched_keywords": [kw for kw in sig.get("keywords", []) if kw.lower() in content_lower],
                    "matched_patterns": [p.pattern[:60] for p in compiled_pats if p.search(content)],
                })
        return hits

    def analyze_batch(
        self,
        contents: List[str],
        propose: bool = True,
    ) -> Tuple[List[PatternCandidate], Dict[str, int]]:
        """
        Analyze a batch of content, aggregate gaps, propose candidates.

        Args:
            contents: List of memory content strings
            propose:  If True, create PatternCandidates for new gaps

        Returns:
            (candidates, hit_counts)
        """
        hit_counts: Dict[str, int] = {}
        examples: Dict[str, List[str]] = {}

        for content in contents:
            hits = self.check(content)
            for hit in hits:
                name = hit["name"]
                hit_counts[name] = hit_counts.get(name, 0) + 1
                if name not in examples:
                    examples[name] = []
                if len(examples[name]) < 5:
                    examples[name].append(content[:200])

        candidates = []
        if propose:
            for sig, _ in self._compiled:
                name = sig["name"]
                if name in hit_counts:
                    c = PatternCandidate(
                        candidate_id  = "LEARN-" + _short_id(),
                        name          = name,
                        description   = sig["description"],
                        category      = sig["category"],
                        severity      = sig["severity"],
                        keywords      = sig.get("keywords", []),
                        patterns      = sig.get("patterns", []),
                        examples      = examples.get(name, []),
                        source        = PatternSource.GAP_DETECTION,
                        proposed_at   = _now(),
                        proposed_by   = "gap_detector",
                        hit_count     = hit_counts[name],
                        mitre_id      = sig.get("mitre_id"),
                        cve_id        = sig.get("cve_id"),
                    )
                    candidates.append(c)

        return candidates, hit_counts


# ---------------------------------------------------------------------------
# Pattern Learner — main entry point
# ---------------------------------------------------------------------------

class PatternLearner:
    """
    Human-supervised pattern learning engine.

    Manages the full lifecycle:
    1. Gap detection (what are we missing?)
    2. Candidate proposal (what should we add?)
    3. Human review (approve / reject / modify)
    4. Runtime application (patterns take effect immediately)
    5. Export (permanent addition to patterns.py)

    Args:
        store_path:      Path to persist learning state (.json)
        on_new_candidate: Callback when a new candidate is proposed
        auto_approve_cve: Auto-approve patterns linked to published CVEs
                          (still logged, still reversible, but no manual step)
    """

    def __init__(
        self,
        store_path: Optional[str] = None,
        on_new_candidate: Optional[Callable[[PatternCandidate], None]] = None,
        auto_approve_cve: bool = False,
    ) -> None:
        self._store = PatternStore(path=store_path)
        self._on_new = on_new_candidate
        self._auto_approve_cve = auto_approve_cve
        self._gap_detector = GapDetector()
        self._runtime_patterns: List[Any] = []  # Threat objects

    # ── Gap detection ───────────────────────────────────────────────────────

    def detect_gaps(self, contents: List[str]) -> List[PatternCandidate]:
        """
        Scan content for attacks the current patterns miss.

        Returns new PatternCandidates (added to store as PENDING).
        """
        candidates, counts = self._gap_detector.analyze_batch(contents, propose=True)
        new = []
        existing_names = {c.name for c in self._store.all_candidates()}

        for candidate in candidates:
            if candidate.name in existing_names:
                # Update hit count on existing candidate
                existing = next(
                    (c for c in self._store.all_candidates() if c.name == candidate.name), None
                )
                if existing:
                    existing.hit_count += candidate.hit_count
                    existing.examples = list(set(existing.examples + candidate.examples))[:5]
                    self._store.update_candidate(existing)
                continue

            # Auto-approve CVE-backed patterns if configured
            if self._auto_approve_cve and candidate.cve_id:
                candidate.review = ReviewDecision.APPROVED
                candidate.reviewed_at = _now()
                candidate.reviewed_by = "auto_cve"

            self._store.add_candidate(candidate)
            new.append(candidate)

            if self._on_new:
                try:
                    self._on_new(candidate)
                except Exception:
                    pass

        return new

    def check_content(self, content: str) -> List[Dict[str, Any]]:
        """
        Check a single content against gap signatures.
        Does NOT create candidates — just returns matches.
        """
        return self._gap_detector.check(content)

    # ── Review ──────────────────────────────────────────────────────────────

    def approve(
        self,
        candidate_id: str,
        reviewer: str = "human",
        notes: str = "",
    ) -> Optional[PatternCandidate]:
        """Approve a candidate pattern. It will be applied on next apply() call."""
        candidate = self._store.get(candidate_id)
        if not candidate:
            return None
        candidate.review = ReviewDecision.APPROVED
        candidate.reviewed_at = _now()
        candidate.reviewed_by = reviewer
        if notes:
            candidate.reject_reason = notes  # reuse field for notes
        self._store.update_candidate(candidate)
        return candidate

    def reject(
        self,
        candidate_id: str,
        reason: str,
        reviewer: str = "human",
    ) -> Optional[PatternCandidate]:
        """Reject a candidate pattern."""
        candidate = self._store.get(candidate_id)
        if not candidate:
            return None
        candidate.review = ReviewDecision.REJECTED
        candidate.reviewed_at = _now()
        candidate.reviewed_by = reviewer
        candidate.reject_reason = reason
        self._store.update_candidate(candidate)
        return candidate

    def modify(
        self,
        candidate_id: str,
        keywords: Optional[List[str]] = None,
        patterns: Optional[List[str]] = None,
        severity: Optional[str] = None,
        reviewer: str = "human",
    ) -> Optional[PatternCandidate]:
        """Modify a candidate before approving."""
        candidate = self._store.get(candidate_id)
        if not candidate:
            return None
        if keywords is not None:
            candidate.keywords = keywords
        if patterns is not None:
            candidate.patterns = patterns
        if severity is not None:
            candidate.severity = severity
        candidate.review = ReviewDecision.MODIFIED
        candidate.reviewed_at = _now()
        candidate.reviewed_by = reviewer
        self._store.update_candidate(candidate)
        return candidate

    # ── False positive tracking ──────────────────────────────────────────────

    def report_false_positive(
        self,
        content: str,
        threat_id: str,
        reported_by: str = "user",
        context: str = "",
    ) -> FalsePositive:
        """
        Report a false positive (safe content that was blocked).

        Aggregates into whitelist candidates for human review.
        """
        fp = FalsePositive(
            fp_id       = "FP-" + _short_id(),
            content     = content[:500],
            threat_id   = threat_id,
            reported_at = _now(),
            reported_by = reported_by,
            context     = context,
        )
        self._store.add_false_positive(fp)
        return fp

    # ── Apply approved patterns ──────────────────────────────────────────────

    def apply(self, analyzer: Any) -> int:
        """
        Apply all approved patterns to a running Analyzer instance.

        Converts approved PatternCandidates to Threat objects and
        adds them to the analyzer's pattern list.

        Returns count of patterns applied.
        """
        from memgar.models import Threat, ThreatCategory, Severity

        already_applied = {
            getattr(p, "id", "") for p in getattr(analyzer, "patterns", [])
        }
        applied = 0

        for candidate in self._store.approved():
            cid = "LEARN-" + candidate.candidate_id[-8:]
            if cid in already_applied:
                continue

            # Map severity
            sev_map = {
                "low": Severity.LOW, "medium": Severity.MEDIUM,
                "high": Severity.HIGH, "critical": Severity.CRITICAL,
            }
            sev = sev_map.get(candidate.severity.lower(), Severity.HIGH)

            # Map category
            cat_map = {
                "MANIPULATION": ThreatCategory.MANIPULATION,
                "INJECTION":    ThreatCategory.INJECTION,
                "EXFILTRATION": ThreatCategory.EXFILTRATION,
                "EVASION":      ThreatCategory.EVASION,
                "SLEEPER":      ThreatCategory.SLEEPER,
                "PRIVILEGE":    ThreatCategory.PRIVILEGE,
                "SOCIAL":       ThreatCategory.SOCIAL,
            }
            cat = cat_map.get(candidate.category.upper(), ThreatCategory.INJECTION)

            threat = Threat(
                id          = cid,
                name        = candidate.name,
                description = candidate.description,
                category    = cat,
                severity    = sev,
                patterns    = candidate.patterns,
                keywords    = candidate.keywords,
                examples    = candidate.examples,
                mitre_attack= candidate.mitre_id or "",
            )

            if not hasattr(analyzer, "patterns"):
                analyzer.patterns = []
            analyzer.patterns.append(threat)

            # Also register keyword in cache
            from memgar.analyzer import _get_keyword_pattern
            for kw in candidate.keywords:
                _get_keyword_pattern(kw)

            applied += 1

        return applied

    # ── Export to patterns.py ────────────────────────────────────────────────

    def export_to_python(self, output_path: Optional[str] = None) -> str:
        """
        Export approved patterns as Python code for patterns.py.

        Returns the generated code string. If output_path is given,
        also writes to that file.
        """
        approved = self._store.approved()
        if not approved:
            return "# No approved patterns to export\n"

        lines = [
            "# =============================================================================",
            "# LEARNED PATTERNS — Human-approved via PatternLearner",
            f"# Generated: {_now()}",
            f"# Count: {len(approved)}",
            "# =============================================================================",
            "",
        ]

        for c in approved:
            var_name = "LEARN_" + re.sub(r"[^A-Z0-9]", "_", c.name.upper())
            sev = c.severity.upper()
            cat = c.category.upper()

            kw_lines = ",\n        ".join(f'"{kw}"' for kw in c.keywords)
            pat_lines = ",\n        ".join(f'r"{p}"' for p in c.patterns)
            ex_lines  = ",\n        ".join(f'"{e[:100]}"' for e in c.examples[:3])

            lines += [
                f"{var_name} = Threat(",
                f'    id="{c.candidate_id[-8:].upper()}",',
                f'    name="{c.name}",',
                f'    description="{c.description}",',
                f"    category=ThreatCategory.{cat},",
                f"    severity=Severity.{sev},",
                f"    keywords=[",
                f"        {kw_lines}",
                f"    ],",
                f"    patterns=[",
                f"        {pat_lines}",
                f"    ],",
                f"    examples=[",
                f"        {ex_lines}",
                f"    ],",
                f'    mitre_attack="{c.mitre_id or ""}",',
                f")",
                "",
            ]

        # Add to PATTERNS list
        var_names = ["LEARN_" + re.sub(r"[^A-Z0-9]", "_", c.name.upper()) for c in approved]
        lines += [
            "PATTERNS.extend([",
            "    " + ",\n    ".join(var_names),
            "])",
            "",
        ]

        code = "\n".join(lines)

        if output_path:
            Path(output_path).write_text(code, encoding="utf-8")

        return code

    # ── Status & introspection ───────────────────────────────────────────────

    def pending(self) -> List[PatternCandidate]:
        return self._store.pending()

    def stats(self) -> LearningStats:
        all_c = self._store.all_candidates()
        return LearningStats(
            candidates_proposed = len(all_c),
            candidates_approved = sum(1 for c in all_c if c.is_approved),
            candidates_rejected = sum(1 for c in all_c if c.review == ReviewDecision.REJECTED),
            candidates_pending  = sum(1 for c in all_c if c.is_pending),
            false_positives     = len(self._store.false_positives()),
            patterns_applied    = len(self._runtime_patterns),
            gaps_detected       = sum(c.hit_count for c in all_c),
        )

    def verify_store(self) -> Tuple[bool, int]:
        """Verify tamper-evidence of the learning store."""
        return self._store.verify_chain()

    def all_candidates(self) -> List[PatternCandidate]:
        return self._store.all_candidates()


# ---------------------------------------------------------------------------
# Convenience: pre-built learner with all gap signatures loaded
# ---------------------------------------------------------------------------

def create_learner(
    store_path: Optional[str] = None,
    **kwargs,
) -> PatternLearner:
    """Create a PatternLearner ready to detect 2026 attack gaps."""
    return PatternLearner(store_path=store_path, **kwargs)


def scan_for_gaps(contents: List[str]) -> List[Dict[str, Any]]:
    """
    Quick scan — returns gap matches without creating candidates.

    Useful for one-off checks without a persistent store.
    """
    detector = GapDetector()
    results = []
    for content in contents:
        hits = detector.check(content)
        if hits:
            results.append({"content_preview": content[:100], "gaps": hits})
    return results


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _now() -> str:
    return datetime.now(tz=timezone.utc).isoformat()


def _short_id() -> str:
    return uuid.uuid4().hex[:8].upper()
